### get personajes
GET http://localhost:3000/api/usuarios

### get personaje con un determinado id
GET http://localhost:3000/api/usuarios/03

### añadir personajes
POST http://localhost:3000/api/usuarios/ 
Content-Type: application/json

{
    "idUser":"04",
    "nick": "Pedro Aznar",
    "nomUser":"pepe.aznr",
    "passwd": "123445",
    "mail": "pedro@aznar.com"
}

### modificar un personaje
PUT http://localhost:3000/api/usuarios/04
Content-Type: application/json

{
    "idUser":"04",
    "nick": "Pedro Aznar",
    "nomUser":"pepe.aznr",
    "passwd": "abcde",
    "mail": "pedro@aznar.com"
}

### borrar
DELETE http://localhost:3000/api/personajes/03