### get personajes
GET http://localhost:3000/api/tablas/buscar/Tablero

GET http://localhost:3000/api/tablas/buscar/

### get personaje con un determinado id
GET http://localhost:3000/api/tablas/abcdef123456abcdef123456

### añadir personajes
POST http://localhost:3000/api/tablas/ 
Content-Type: application/json

{
    "sessionId": "abcdef123456abcdef123456",
    "sessionDate": "2023-11-09",
    "sessionName": "Tablero de Carlos"
}

### modificar un personaje
PUT http://localhost:3000/api/tablas/abcdef123456abcdef123456
Content-Type: application/json

{
    "sessionId": "abcdef123456abcdef123456",
    "sessionDate": "2023-10-09",
    "sessionName": "Tablero de Carlos"
}

### borrar
DELETE http://localhost:3000/api/tablas/abcdef123456abcdef123456