### get personajes
GET http://localhost:3000/api/notas/

GET http://localhost:3000/api/tablas/buscar/

### get personaje con un determinado id
GET http://localhost:3000/api/tablas/abcdef123456abcdef123456

### añadir personajes
POST http://localhost:3000/api/notas/21
Content-Type: application/json

{
    "desc": "Anotar esto muy importante",
    "position": 2
}

### modificar un personaje
PUT http://localhost:3000/api/notas/02
Content-Type: application/json

{
    "idItem": "02",
    "idSession": "2",
    "desc": "Anotar esto muy importante",
    "position": 2
}

### borrar
DELETE http://localhost:3000/api/notas/11