### get personajes
GET http://localhost:3000/api/personajes

### get personaje con un determinado id
GET http://localhost:3000/api/personajes/03

### añadir personajes
POST http://localhost:3000/api/personajes/ 
Content-Type: application/json

{
    "idPers":"03",
    "nomPers": "Pedro Aznar",
    "desc":"El amo todopoderoso indiscutido dentro de la galaxia de las voces",
    "HP":500,
    "ATK":54,
    "EVD":32,
    "DEF":30,
    "VD":22,
    "REC":11
}

### modificar un personaje
PUT http://localhost:3000/api/personajes/03
Content-Type: application/json

{
    "idPers":"03",
    "nomPers": "Pedro Aznar",
    "desc":"El amo todopoderoso indiscutido dentro de la galaxia de las voces",
    "HP":1000,
    "ATK":54,
    "EVD":32,
    "DEF":30,
    "VD":22,
    "REC":11
}

### borrar
DELETE http://localhost:3000/api/personajes/03